str = ''
str += '<div id="footer">'
str += '	<div class="footer_wrap">'
str += '		<div class="f_logo">SK infosec</div>'
str += '		<div class="f_info">'
str += '			<ul class="add">'
str += '				<li>SK인포섹(주) 13486 경기도 성남시 분당구 판교로255번길 46 4층</li>'
str += '				<li><a href="javascript:" onclick="javascript:fn_popup(\'popup_view.html\',\'popup1\',\'550\',\'500\',60,100); return false;" title="새 창 열림">개인정보 처리방침</a><span class="bar"></span></li>'
str += '			</ul>'
str += '			<p>사업자등록번호 : 120-86-07747 TEL : 02-6361-9114 FAX : 02-6361-9999</p>'
str += '			<p class="copy">COPYRIGHT © 2018 SK infosec. All Rights Reserved</p>'
str += '		</div>'
str += '		<div class="mark">'
str += '			<ul>'
str += '				<li><a href="#none"><i class="ico sns sns_01">블로그</i></a></li>'
str += '				<li><a href="#none"><i class="ico sns sns_02">페이스북</i></a></li>'
str += '				<li><a href="#none"><i class="ico sns sns_03">유튜브</i></a></li>'
str += '			</ul>'
str += '		</div>'
str += '		<div class="f_btn">'
str += '			<a href="contact.html">문의하기</a>'
str += '		</div>'
str += '	</div>'
str += '</div>'

document.write(str);